apiVersion: apps/v1
kind: Deployment
metadata:
  name: hzyjavawebfinal
  namespace: hzy
  labels:
    app: hzyjavawebfinal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hzyjavawebfinal
  template:
    metadata:
      labels:
        app: hzyjavawebfinal
    spec:
      containers:
        - name: hzyjavawebfinal
          image: talangtuandui-docker.pkg.coding.net/hzyjavaweb/main/hzyjavawebfinal:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: coding-hzy-javawebfinal
      nodeName: node5