apiVersion: apps/v1
kind: Deployment
metadata:
  name: hzy-javawebfinal
  namespace: hzy
  labels:
    app: hzy-javawebfinal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hzy-javawebfinal
  template:
    metadata:
      labels:
        app: hzy-javawebfinal
    spec:
      containers:
        - name: hzy-javawebfinal
          image: talangtuandui-docker.pkg.coding.net/hzyjavaweb/main/hzyjavawebfinal:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: coding-hzy-javawebfinal
      nodeName: node5