apiVersion: v1
kind: Service
metadata:
  name: hzyJavaWebFinal
  namespace: hzy
spec:
  selector:
    app: hzyJavaWebFinal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: hzyJavaWebFinal-80
  type: NodePort