apiVersion: v1
kind: Service
metadata:
  name: hzyjavawebfinal
  namespace: hzy
spec:
  selector:
    app: hzyjavawebfinal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: hzyjavawebfinal-80
  type: NodePort