apiVersion: v1
kind: Service
metadata:
  name: hzy-javawebfinal
  namespace: hzy
spec:
  selector:
    app: hzy-javawebfinal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: hzy-javawebfinal-80
  type: NodePort