#server:
#  servlet:
#    context-path: /JavaWebFinal
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.180.244.15:3306/hzy_web
    username: hzy
    password: 111222333
  mvc:
    view:
      prefix: /
      suffix: .jsp
  application:
    name: JavaWebFinal
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/webapp/